### ISSUE TITLE
Multi-paged Resource Buyers List

### ISSUE THREAD

**Issue by TheJavaHacker** [Maximvdw/SpigotSite-API#11]
Hey there,

I am trying to utilise this resource to verify the buyers of my plugins, however if someone on another page of buyers list (not page 1), it errors and can't find the buyer.

I was hoping you would know a work around or could push an update to fix this?

Thanks.

**Comment by Maximvdw** [comment]
It should have been fixed in the latest implementation https://github.com/Maximvdw/SpigotSite
